version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:16-alpine
    container_name: application
    environment:
      - DBUSER=postgres
      - DBPASS=postgres
      - DBIP=db
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - "80:3000"
    networks:
      - app-network
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creativewriting
    volumes:
      - ./DatabaseDevScript.sql:/docker-entrypoint-initdb.d/DatabaseDevScript.sql
    networks:
      - app-network
    command: -p 5432

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
