version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    environment:
      - DBUSER=postgres
      - DBPASS=postgres
      - DBIP=db
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - '80:3000'
    networks:
      - app-network
  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creativewriting
    volumes:
      - ./DatabaseDevScript.sql:/docker-entrypoint-initdb.d/DatabaseDevScript.sql
    # port forwarded for dev purposes to connect to outside of WSL
    ports:
      - '6000:5432'
    networks:
      - app-network
  converter:
    image: lynxtaa/unoserver-web
    container_name: converter
    environment:
      - PORT=4000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
