version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DBUSER=postgres
      - DBPASS=postgres
      - DBIP=db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creativewriting
    volumes:
      - ./DatabaseDevScript.sql:/docker-entrypoint-initdb.d/DatabaseDevScript.sql
    expose:
      - "5432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5432:5432"
    command: -p 5432
  nginx:
    image: nginx:1.17.1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app